services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: laravel_backend_takmir
        volumes:
            - .:/var/www/html
        ports:
            - "8000:80"
        environment:
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_DATABASE: db_takmir
            DB_USERNAME: root
            DB_PASSWORD: root
        depends_on:
            - mysql
            - phpmyadmin
        networks:
            - laravel

    mysql:
        image: mysql:8
        container_name: takmir_mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: db_takmir
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        ports:
            - "3307:3306"
        volumes:
            - ./mysql_data:/var/lib/mysql
        networks:
            - laravel

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: takmir_phpmyadmin
        restart: always
        ports:
            - "8001:80"
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: root
        depends_on:
            - mysql
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
