[variables]
PHP_VERSION = "8.2"
NIXPACKS_PHP_ROOT_DIR = "/app"

[phases.setup]
nixPkgs = ["php82", "composer", "nodejs_18"]
aptPkgs = ["default-mysql-client"]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader",
]

[phases.build]
cmds = [
    "php artisan config:cache",
    "php artisan route:cache", 
    "php artisan view:cache"
]

[phases.deploy]
cmds = [
    "php artisan config:cache --no-interaction",
    "php artisan migrate --force --no-interaction || echo 'Migration failed, continuing...'",
    "php artisan storage:link --force || echo 'Storage link failed, continuing...'"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"